name: Build

on: [push, pull_request]

jobs:
  build-vpygen:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Build Package
        run: |
          corepack enable
          yarn
          yarn build
          yarn pack --filename koishi-plugin-beian.tgz
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: koishi-plugin-beian-${{ github.sha }}
          path: koishi-plugin-beian.tgz
